"""
certificate.py - Professional EPR Certificate + Offer Receipt (white, print-ready PDF)
"""
import io
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from fpdf import FPDF

from app.database import get_db
from app import models

router = APIRouter(prefix="/certificate", tags=["Certificate"])


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _safe(text: str) -> str:
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2019": "'", "\u2018": "'",
        "\u201c": '"', "\u201d": '"', "\u20b9": "INR", "\u2192": "->",
        "\u2022": "*", "&": "and",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _fmt_inr(amount: float) -> str:
    return f"Rs. {amount:,.2f}"


def _fmt_date(dt) -> str:
    if not dt:
        return datetime.utcnow().strftime("%d %B %Y")
    return dt.strftime("%d %B %Y")


# ─── PDF Class ────────────────────────────────────────────────────────────────

class CertPDF(FPDF):
    def header(self):
        pass  # custom header per page

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(120, 120, 120)
        self.set_draw_color(180, 180, 180)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(2)
        self.set_x(15)
        self.cell(0, 5,
            f"System-generated by Terionix-MRIS  |  E-Waste (Management) Rules 2022, MoEFCC, Govt. of India  |  Page {self.page_no()}",
            align="C")

    def page_header_block(self, subtitle: str):
        """Top letterhead for each page."""
        # Logo area — left side
        self.set_xy(15, 18)
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(20, 20, 20)
        self.cell(80, 10, "TERIONIX", ln=False)

        # Right side — registration info
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(80, 80, 80)
        self.set_xy(110, 18)
        self.cell(85, 5, "Terionix Material Recovery Pvt. Ltd.", ln=True, align="R")
        self.set_x(110)
        self.cell(85, 4, "EPR Reg. No.: CPCB/EPR/TRX/2024/0047", ln=True, align="R")
        self.set_x(110)
        self.cell(85, 4, "GSTIN: 27AAACT1234F1ZK", ln=True, align="R")
        self.set_x(110)
        self.cell(85, 4, "support@terionix.in  |  +91-80-4567-8901", ln=True, align="R")

        # Tagline under logo
        self.set_xy(15, 28)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(100, 100, 100)
        self.cell(80, 5, "Material Recovery Intelligence System")

        # Horizontal rule
        self.set_draw_color(40, 40, 40)
        self.set_line_width(0.6)
        self.line(15, 37, 195, 37)
        self.set_line_width(0.2)
        self.ln(0)
        self.set_y(38)

        # Document title
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(20, 20, 20)
        self.set_x(15)
        self.cell(0, 9, _safe(subtitle), align="C", ln=True)

        # Light rule under title
        self.set_draw_color(160, 160, 160)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(5)

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 8.5)
        self.set_text_color(30, 30, 30)
        self.set_x(15)
        # Underline via draw
        y = self.get_y()
        self.cell(0, 6, _safe(title.upper()), ln=True)
        self.set_draw_color(180, 180, 180)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(2)

    def kv(self, key: str, value: str, key_w: int = 72):
        self.set_x(18)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(90, 90, 90)
        self.cell(key_w, 6, _safe(key) + ":")
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(20, 20, 20)
        self.cell(0, 6, _safe(str(value)), ln=True)

    def spacer(self, h: int = 4):
        self.ln(h)


# ─── Certificate Pages ────────────────────────────────────────────────────────

def generate_certificate_pdf(batch: models.Batch, supplier: models.Supplier) -> bytes:
    pdf = CertPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(15, 15, 15)

    cert_num   = f"TRX/EPR/{batch.batch_id[:8].upper()}/{datetime.utcnow().year}"
    issue_date = _fmt_date(batch.completed_at or datetime.utcnow())

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 1 — EPR Certificate
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.page_header_block("EXTENDED PRODUCER RESPONSIBILITY (EPR) CERTIFICATE")

    # Cert number / date bar (light grey box)
    pdf.set_fill_color(245, 245, 245)
    pdf.set_draw_color(200, 200, 200)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(50, 50, 50)
    bar_y = pdf.get_y()
    pdf.cell(60, 7, f"  Certificate No: {cert_num}", fill=True, border=1)
    pdf.cell(60, 7, f"  Issue Date: {issue_date}", fill=True, border=1)
    pdf.cell(60, 7, f"  Batch Ref: {batch.batch_id[:12].upper()}...", fill=True, border=1)
    pdf.ln(9)

    # ── Section 1 ─────────────────────────────────────────────────────────────
    pdf.spacer(3)
    pdf.section_title("1.  Certificate and Recycler Details")
    pdf.kv("Certificate Number",    cert_num)
    pdf.kv("Date of Issue",         issue_date)
    pdf.kv("Batch Reference ID",    batch.batch_id.upper())
    pdf.kv("Authorized Recycler",   "Terionix Material Recovery Pvt. Ltd.")
    pdf.kv("EPR Registration No.",  "CPCB/EPR/TRX/2024/0047")
    pdf.kv("Recycler Category",     "Authorized Dismantler and Recycler (Category A)")
    pdf.kv("Issuing Authority",     "Central Pollution Control Board (CPCB)")
    pdf.spacer(5)

    # ── Section 2 ─────────────────────────────────────────────────────────────
    pdf.section_title("2.  Producer / IT Company Details")
    pdf.kv("Company Name",          _safe(supplier.name))
    pdf.kv("Supplier ID",           supplier.supplier_id[:20].upper())
    pdf.kv("EPR Portal",            "MoEFCC EPR Portal (eprewaste.gov.in)")
    pdf.kv("Producer Category",     "IT Equipment / Consumer Electronics")
    pdf.spacer(5)

    # ── Section 3 ─────────────────────────────────────────────────────────────
    pdf.section_title("3.  E-Waste Description")
    pdf.kv("Device Category",       batch.device_type.replace("_", " ").title())
    pdf.kv("Condition at Intake",   batch.condition.title())
    pdf.kv("Gross Weight Collected",f"{batch.weight:.2f} kg")
    pdf.kv("Batch Segment",         batch.segment or "N/A")
    pdf.kv("Collection Date",       _fmt_date(batch.submitted_at))
    if batch.completed_at:
        pdf.kv("Recovery Completion", _fmt_date(batch.completed_at))
    pdf.spacer(5)

    # ── Section 4 ─────────────────────────────────────────────────────────────
    pdf.section_title("4.  Valuation Summary")
    pdf.kv("Expected Recovery Value (ERV)", _fmt_inr(batch.expected_value or 0))
    pdf.kv("Guaranteed Offer Price",        _fmt_inr(batch.offer_price or 0))
    if batch.actual_value:
        pdf.kv("Actual Recovery Value",     _fmt_inr(batch.actual_value))
        err = abs((batch.actual_value - (batch.expected_value or 1)) / (batch.expected_value or 1)) * 100
        pdf.kv("Prediction Accuracy",       f"{100 - err:.1f}%")
    pdf.kv("Currency",                      "Indian Rupees (INR)")
    pdf.spacer(5)

    # ── Section 5 — Declaration ───────────────────────────────────────────────
    pdf.section_title("5.  Compliance Declaration")
    pdf.set_x(18)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(30, 30, 30)
    declaration = _safe(
        "This is to certify that the e-waste described above has been collected, transported, and processed "
        "in compliance with the E-Waste (Management) Rules 2022 and all applicable directives issued by the "
        "Ministry of Environment, Forest and Climate Change (MoEFCC), Government of India. "
        "The material has been handed over to a CPCB-authorized recycler and dismantler. "
        "The producer named herein has fulfilled their Extended Producer Responsibility (EPR) obligations "
        "for the quantity of e-waste specified in this certificate. "
        "This certificate may be used as valid evidence of EPR compliance for the processing period."
    )
    pdf.multi_cell(177, 5.5, declaration)
    pdf.spacer(8)

    # ── Signature block ───────────────────────────────────────────────────────
    pdf.set_draw_color(150, 150, 150)
    pdf.set_line_width(0.3)
    sig_y = pdf.get_y()

    # Left sig
    pdf.line(18, sig_y + 14, 90, sig_y + 14)
    pdf.set_x(18)
    pdf.set_y(sig_y + 16)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(72, 5, _safe(supplier.name))
    pdf.ln(4)
    pdf.set_x(18)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(72, 5, "Authorized Signatory (Producer)")

    # Right sig
    pdf.set_y(sig_y)
    pdf.set_x(115)
    pdf.line(115, sig_y + 14, 190, sig_y + 14)
    pdf.set_y(sig_y + 16)
    pdf.set_x(115)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(72, 5, "Terionix Material Recovery Pvt. Ltd.")
    pdf.ln(4)
    pdf.set_x(115)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(72, 5, "Authorized Signatory (Recycler)")

    # Stamp placeholder
    pdf.set_y(sig_y)
    pdf.set_x(87)
    pdf.set_draw_color(180, 180, 180)
    pdf.set_line_width(0.3)
    pdf.circle(97, sig_y + 10, 8)
    pdf.set_font("Helvetica", "", 5.5)
    pdf.set_text_color(150, 150, 150)
    pdf.set_xy(90, sig_y + 7)
    pdf.cell(14, 4, "OFFICE", align="C", ln=True)
    pdf.set_x(90)
    pdf.cell(14, 4, "SEAL", align="C")

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 2 — Offer Amount Receipt
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.page_header_block("OFFER AMOUNT RECEIPT")

    receipt_num = f"RCP/{batch.batch_id[:6].upper()}/{datetime.utcnow().strftime('%Y%m')}"

    # Receipt meta bar
    pdf.set_fill_color(245, 245, 245)
    pdf.set_draw_color(200, 200, 200)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(90, 7, f"  Receipt No: {receipt_num}", fill=True, border=1)
    pdf.cell(90, 7, f"  Date: {issue_date}", fill=True, border=1)
    pdf.ln(9)

    pdf.spacer(4)
    pdf.section_title("Bill To")
    pdf.kv("Company / Producer", _safe(supplier.name))
    pdf.kv("Batch Reference",    batch.batch_id.upper())
    pdf.spacer(5)

    # ── Line items table ──────────────────────────────────────────────────────
    pdf.section_title("Item Description")

    # Table header
    pdf.set_fill_color(30, 30, 30)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_x(15)
    pdf.cell(85, 7, "  Description", fill=True, border=0)
    pdf.cell(35, 7, "Weight", fill=True, border=0, align="C")
    pdf.cell(25, 7, "Unit", fill=True, border=0, align="C")
    pdf.cell(35, 7, "Amount (Rs.)", fill=True, border=0, align="R")
    pdf.ln()

    # Row 1
    pdf.set_fill_color(252, 252, 252)
    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_draw_color(210, 210, 210)
    desc = f"{batch.device_type.title()} ({batch.condition.title()} condition)"
    pdf.set_x(15)
    pdf.cell(85, 7, f"  {_safe(desc)}", fill=True, border="B")
    pdf.cell(35, 7, f"{batch.weight:.2f} kg", fill=True, border="B", align="C")
    pdf.cell(25, 7, "Batch", fill=True, border="B", align="C")
    pdf.cell(35, 7, f"{batch.offer_price or 0:,.2f}  ", fill=True, border="B", align="R")
    pdf.ln(10)

    # ── Totals ────────────────────────────────────────────────────────────────
    offer         = batch.offer_price or 0
    gst_amt       = round(offer * 0.18, 2)
    total_payable = round(offer + gst_amt, 2)

    for label, val, bold in [
        ("Sub-Total",             f"Rs. {offer:,.2f}",         False),
        ("IGST @ 18%",            f"Rs. {gst_amt:,.2f}",        False),
        ("Total Payable",         f"Rs. {total_payable:,.2f}",  True),
    ]:
        pdf.set_x(115)
        pdf.set_font("Helvetica", "B" if bold else "", 9 if bold else 8.5)
        pdf.set_text_color(20, 20, 20)
        pdf.set_draw_color(200, 200, 200)
        border = "B" if not bold else 0
        if bold:
            pdf.set_fill_color(240, 240, 240)
            pdf.set_x(115)
            pdf.cell(80, 8, "", fill=True)
            pdf.set_x(115)
            pdf.set_y(pdf.get_y() - 8)
        pdf.cell(45, 8, label, border=border)
        pdf.cell(35, 8, _safe(val), border=border, align="R", ln=True)

    pdf.spacer(3)

    # Amount in words
    pdf.set_x(15)
    pdf.set_fill_color(248, 248, 248)
    pdf.set_draw_color(200, 200, 200)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(180, 7, f"  Amount in Words: {_inr_words(total_payable)} Only", fill=True, border=1, ln=True)
    pdf.spacer(6)

    # ── Payment details ───────────────────────────────────────────────────────
    pdf.section_title("Payment and Bank Details")
    pdf.kv("Payment Method",  "NEFT / RTGS / Bank Transfer")
    pdf.kv("Bank Name",       "HDFC Bank Ltd.")
    pdf.kv("Account Name",    "Terionix Material Recovery Pvt. Ltd.")
    pdf.kv("Account Number",  "XXXX XXXX 4892")
    pdf.kv("IFSC Code",       "HDFC0001234")
    pdf.kv("Payment Ref.",    receipt_num)
    pdf.kv("Due Date",        "Within 7 working days of receipt")
    pdf.spacer(6)

    # ── Terms ─────────────────────────────────────────────────────────────────
    pdf.set_x(15)
    pdf.set_font("Helvetica", "I", 7.5)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(180, 4.5, _safe(
        "Terms and Conditions: This receipt is a valid acknowledgement of offer payment for e-waste "
        "collection services rendered by Terionix Material Recovery Pvt. Ltd. GST is charged as per "
        "applicable government rates. This is a computer-generated document. For disputes or queries, "
        "please contact support@terionix.in within 30 days of the receipt date."
    ))
    pdf.spacer(10)

    # ── Signature ─────────────────────────────────────────────────────────────
    pdf.set_draw_color(150, 150, 150)
    pdf.set_line_width(0.3)
    sig_y2 = pdf.get_y()

    pdf.line(18, sig_y2 + 14, 90, sig_y2 + 14)
    pdf.set_xy(18, sig_y2 + 16)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(72, 5, _safe(supplier.name))
    pdf.ln(4)
    pdf.set_x(18)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(72, 5, "Authorized Signatory (Producer)")

    pdf.set_y(sig_y2)
    pdf.line(115, sig_y2 + 14, 190, sig_y2 + 14)
    pdf.set_xy(115, sig_y2 + 16)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(72, 5, "Terionix Material Recovery Pvt. Ltd.")
    pdf.ln(4)
    pdf.set_x(115)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(72, 5, "Authorized Signatory (Recycler)")

    return bytes(pdf.output())


# ─── Amount in words ──────────────────────────────────────────────────────────

def _inr_words(amount: float) -> str:
    total_paise = int(round(amount * 100))
    rupees = total_paise // 100
    paise  = total_paise % 100

    ones = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
            "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen",
            "Seventeen", "Eighteen", "Nineteen"]
    tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"]

    def two(n):
        return ones[n] if n < 20 else (tens[n // 10] + (" " + ones[n % 10] if n % 10 else "")).strip()

    def words(n):
        if n == 0:           return ""
        elif n < 100:        return two(n)
        elif n < 1000:       r = words(n % 100);   return ones[n//100]      + " Hundred"  + (" " + r if r else "")
        elif n < 100000:     r = words(n % 1000);  return words(n//1000)    + " Thousand" + (" " + r if r else "")
        elif n < 10000000:   r = words(n % 100000);return words(n//100000)  + " Lakh"     + (" " + r if r else "")
        else:                r = words(n%10000000); return words(n//10000000)+ " Crore"    + (" " + r if r else "")

    result = "Indian Rupees " + words(rupees)
    if paise:
        result += " and " + two(paise) + " Paise"
    return result


# ─── Endpoint ─────────────────────────────────────────────────────────────────

@router.get("/{batch_id}")
def download_certificate(batch_id: str, db: Session = Depends(get_db)):
    """Download EPR Certificate + Offer Receipt as a professional white PDF."""
    batch = db.query(models.Batch).filter_by(batch_id=batch_id).first()
    if not batch:
        raise HTTPException(status_code=404, detail=f"Batch '{batch_id}' not found.")

    supplier = db.query(models.Supplier).filter_by(supplier_id=batch.supplier_id).first()
    if not supplier:
        raise HTTPException(status_code=404, detail="Supplier not found.")

    pdf_bytes = generate_certificate_pdf(batch, supplier)
    filename  = f"Terionix_EPR_{batch.batch_id[:8].upper()}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
